// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace message {

static const char* getVerifyService_method_names[] = {
  "/message.getVerifyService/getVerifyCode",
};

std::unique_ptr< getVerifyService::Stub> getVerifyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< getVerifyService::Stub> stub(new getVerifyService::Stub(channel, options));
  return stub;
}

getVerifyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getVerifyCode_(getVerifyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status getVerifyService::Stub::getVerifyCode(::grpc::ClientContext* context, const ::message::getVerifyReq& request, ::message::getVerifyResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::getVerifyReq, ::message::getVerifyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getVerifyCode_, context, request, response);
}

void getVerifyService::Stub::async::getVerifyCode(::grpc::ClientContext* context, const ::message::getVerifyReq* request, ::message::getVerifyResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::getVerifyReq, ::message::getVerifyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getVerifyCode_, context, request, response, std::move(f));
}

void getVerifyService::Stub::async::getVerifyCode(::grpc::ClientContext* context, const ::message::getVerifyReq* request, ::message::getVerifyResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getVerifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::getVerifyResp>* getVerifyService::Stub::PrepareAsyncgetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::getVerifyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::getVerifyResp, ::message::getVerifyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getVerifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::getVerifyResp>* getVerifyService::Stub::AsyncgetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::getVerifyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetVerifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

getVerifyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      getVerifyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< getVerifyService::Service, ::message::getVerifyReq, ::message::getVerifyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](getVerifyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::getVerifyReq* req,
             ::message::getVerifyResp* resp) {
               return service->getVerifyCode(ctx, req, resp);
             }, this)));
}

getVerifyService::Service::~Service() {
}

::grpc::Status getVerifyService::Service::getVerifyCode(::grpc::ServerContext* context, const ::message::getVerifyReq* request, ::message::getVerifyResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message
#include <grpcpp/ports_undef.inc>

